FROM --platform=linux/arm64 rust:bookworm

# Como el contenedor ES arm64, instalamos las dependencias normales sin poner ":arm64"
RUN apt-get update && apt-get install -y     build-essential     pkg-config     libssl-dev     libgtk-3-dev     libwebkit2gtk-4.1-dev     libayatana-appindicator3-dev     librsvg2-dev

WORKDIR /app
